name: Terraform CI/CD

on: 
  [workflow_dispatch]

env:
  TF_VERSION: '1.9.5'
  AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
  AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
  TF_IN_AUTOMATION: true

jobs:
  Apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '${{ env.TF_VERSION }}'

      - name: Validate
        run: terraform --version && terraform init && terraform validate

      - name: Plan
        run: terraform plan

      - name: Apply
        run: terraform apply -auto-approve
  
  Destroy:
    runs-on: ubuntu-latest
    needs: [Apply]

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_versions: '${{ env.TF_VERSION }}'

      - name: Destroy
        run: terraform destroy --auto-approve
        if: github.event_name == 'workflow_dispatch'
