name: Terraform Destroy

on: workflow_dispatch

env: 
  TF_VERSION: '1.9.5'
  AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
  AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
  TF_IN_AUTOMATION: true

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:      
      run:        
        shell: bash 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform        
        uses: hashicorp/setup-terraform@v1        
        with:          
          terraform_version: '${{ env.TF_VERSION }}' 
          
      - name: Destroy        
        run: terraform init && terraform destroy --auto-approve
